services:
  mysql:
    image: mysql:8.4
    container_name: billing-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: billing_db
      MYSQL_USER: billing_user
      MYSQL_PASSWORD: billing_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: