apiVersion: v1
kind: ConfigMap

metadata:
  name: billing-api-config
  namespace: billing
  labels:
    app.kubernetes.io/name: billing-api
    app.kubernetes.io/part-of: billing-app

data:
  APP_ENV: production
  APP_PORT: "8080"
  GIN_MODE: release
  DB_HOST: host.docker.internal
  DB_PORT: "3306"
  DB_MAX_OPEN_CONNS: "25"
  DB_MAX_IDLE_CONNS: "5"
  DB_CONN_MAX_LIFETIME: 5m
  SERVER_SHUTDOWN_TIMEOUT: 15s
