apiVersion: v1
kind: Service

metadata:
  name: billing-api
  namespace: billing

spec:
  selector:
    app: billing-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: ClusterIP
