name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run go vet
        run: go vet ./...

      - name: Build Docker image
        run: docker build -t billing-api:ci .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag billing-api:ci ghcr.io/vijaya-prathap/billing-api:latest
          docker push ghcr.io/vijaya-prathap/billing-api:latest
